version: '3'
services:
  mongodb:
    container_name: books-db
    image: mongo:5
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_DB_COLLECTION_NAME: books
    volumes:
      - ./backend/mongo:/data/db